version: '3'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  events:
    build: ./events
    ports:
      - "3000:3000"
    volumes:
      - ./events:/usr/src/events
      - /usr/src/events/node_modules
